### ISSUE TITLE
About how to visualize mesh?

### ISSUE THREAD

**Issue by chenjiale0303** [yuanqili78/SED-Net#1]
Thanks for sharing the code with us. I have a question about the visualization.
I tried to use **gen_test_vis.py** to generate visual results to observe, but it seems to generate a txt file format, I want to know how to generate mesh file formats such as ply, obj.

**Comment by yuanqili78** [comment]
Hello, the txt file is the color-coded point cloud, which can be visualized in meshlab.



---Original---
From: ***@***.***&gt;
Date: Fri, Oct 20, 2023 09:25 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [yuanqili78/SED-Net] About how to convert txt file to obj orotherformats for file visualization? (Issue #1)




 
Thanks for sharing the code with us. I have a question about the visualization.
 I tried to use gen_test_vis.py to generate visual results to observe, but it seems to generate a txt file format, I want to know how to generate obj, ply, and so on, or is there a direct way to generate these file formats?

**Comment by Roy-zZZ08** [comment]
Thanks for the great work. I want to know how to get the final fitted CAD model result output in the article. This part does not seem to be in your code. Perhaps it is similar to the method in https://github.com/Hippogriff/parsenet-codebase, but the dataset of parsenet-codebase seems to be no longer downloadable.

**Comment by yuanqili78** [comment]
Hello,
Network codes are included in Github. The mesh construction codes have not been&nbsp;tidied and commented. I am sorry for that I am&nbsp;swamped&nbsp;these weeks. By the way, we uploaded our data and ParseNet's data on Onedrive, which has been updated in the Github page of SED-Net yesterday.&nbsp;
Best,
Yuanqi




liyuanqi_nju
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuanqili78/SED-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月25日(星期三) 晚上7:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuanqili78/SED-Net] About how to visualize mesh? (Issue #1)





 
Thanks for the great work. I want to know how to get the final fitted CAD model result output in the article. This part does not seem to be in your code. Perhaps it is similar to the method in https://github.com/Hippogriff/parsenet-codebase, but the dataset of parsenet-codebase seems to be no longer downloadable.

**Comment by Roy-zZZ08** [comment]
Thanks for your reply and looking forward to further updates on the code！

**Comment by chenjiale0303** [comment]
Thanks for your fast reply and looking forward to further updates on the code, too！
