### ISSUE TITLE
Dataset download instructions are confusing

### ISSUE THREAD

**Issue by SamuelBrander** [yuanqili78/SED-Net#2]
The part of the readme about downloading the datasets first links three Baiduyun download links, then the same three links but on OneDrive. This confused me at first, as I had the impression I had to download six folders from Baiduyun. Due to that cloud platform trying to force me to download their app, I began setting up a dedicated virtual machine for this purpose, as I do not wish to download the Baiduyun software onto my normal system. However, upon realizing the data is also available on OneDrive, that work proved unnecessary in hindsight. It would be much clearer if you could shorten the instructions to just three lines, one for each folder, and say "Download ... from Baiduyun or OneDrive", and make it clearer the data is available both on Baiduyun and OneDrive.

**Comment by yuanqili78** [comment]
Thank you very much for pointing out this. I have modified the readme.

**Comment by SamuelBrander** [comment]
Thanks, this is much clearer.
