### ISSUE TITLE
执行出现未知错误

### ISSUE THREAD

**Issue by PPzpower** [yuanqili78/SED-Net#5]
您好，十分感谢您的工作成果分享！
我在执行测试代码时出现了如下错误，您有分享的建议解决这个问题吗？
我执行python generate_predictions_aug.py configs/config_SEDNet_normal.yml NoSave no_multi_vote no_fold5drop
后出现错误：*** Error in `python': free(): invalid pointer: 0x000055e38fa04128 ***

**Comment by PPzpower** [comment]
![Uploading 111.png…]()

**Comment by MingFengHill** [comment]
This could be caused by a version conflict between torch and open3d, I solved this by reinstalling open3d.
```
pip uninstall open3d
pip install open3d
```

**Comment by PPzpower** [comment]
> This could be caused by a version conflict between torch and open3d, I solved this by reinstalling open3d.
> 
> ```
> pip uninstall open3d
> pip install open3d
> ```

好的非常感谢
